language: go
go:
  - "1.10.3"

sudo: required
dist: trusty

os:
  - linux
  - osx

# Caching so the next build will be fast as possible.
cache:
  timeout: 1000
  directories:
    - $HOME/usr
    - $HOME/testdata
    - /usr/local/Cellar

env:
  global:
    - PACKAGE_VERSION=0.1.$TRAVIS_BUILD_NUMBER$TRAVIS_TAG # Special builds will have a tag
    - OPENCV_VERSION=3.4.2

addons:
  apt:
    packages:
    - libgmp-dev
    - build-essential
    - cmake
    - git
    - libgtk2.0-dev
    - libgtk-3-dev
    - pkg-config
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libtbb2
    - libtbb-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libdc1394-22-dev
    - xvfb
    - python-setuptools
install:
  - bash .travis/before_install.sh
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/axw/gocov/gocov
  - go get github.com/golang/mock/gomock
  - go install github.com/golang/mock/mockgen
  - dep ensure
  - .travis/compile_opencv.sh
  - export PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config):$HOME/usr/lib/pkgconfig
  - export INCLUDE_PATH=$HOME/usr/include:${INCLUDE_PATH}
  - export LD_LIBRARY_PATH=$HOME/usr/lib:${LD_LIBRARY_PATH}
  - mkdir build
  - .travis/build_project.sh ~/usr/lib/ .dylib
before_script:
  - .travis/get_test_reporter.sh
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: 
  - go generate ./...
  - go test  -coverprofile c.out ./...
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: # Compile a list of changes, tarball everything, make md5 and upload to artifact repo 
  - echo $TRAVIS_COMMIT_RANGE > build/CHANGELOG
  - mkdir lipovision-$PACKAGE_VERSION
  - pushd build && tar -cf ../lipovision-$PACKAGE_VERSION/lipovision-$PACKAGE_VERSION.tar.gz . && popd 
  - pushd lipovision-$PACKAGE_VERSION && md5sum --tag * > lipovision-$PACKAGE_VERSION.md5 && cat lipovision-$PACKAGE_VERSION.md5
  - s3cmd put --recursive . s3://$SPACES_BUCKET/$TRAVIS_OS_NAME/lipovision-$PACKAGE_VERSION/ --access_key=$SPACES_ACCESS_KEY --secret_key=$SPACES_SECRET_KEY --host=$SPACES_ENDPOINT --host-bucket=$SPACES_BUCKET.$SPACES_ENDPOINT
  - popd
